<?php
session_start();
require('fpdf/fpdf.php'); // Include FPDF library

if(!isset($_SESSION['meal_plan'])){
    echo "No meal plan found!";
    exit;
}

$meal_plan = $_SESSION['meal_plan'];

// Create PDF
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial','B',18);
$pdf->Cell(0,10,"TasteIt Weekly Grocery List",0,1,'C');
$pdf->Ln(5);

$pdf->SetFont('Arial','B',14);

foreach($meal_plan as $day => $courses){
    $pdf->SetFillColor(176,195,100); // TasteIt green background
    $pdf->SetTextColor(255,255,255);
    $pdf->Cell(0,10,$day,0,1,'C',true);
    $pdf->Ln(2);
    
    $pdf->SetFont('Arial','',12);
    $pdf->SetTextColor(0,0,0);
    
    foreach($courses as $course => $recipe){
        $pdf->SetFont('Arial','B',12);
        $pdf->Cell(0,8,$course.": ".$recipe['title'],0,1);
        $pdf->SetFont('Arial','',12);
        
        // Ingredients list
        $ingredients = explode("\n",$recipe['ingredients']);
        foreach($ingredients as $ing){
            $ing = trim($ing);
            if(!$ing) continue;
            $pdf->Cell(5); // indent
            $pdf->Cell(0,6,"- ".$ing,0,1);
        }
        $pdf->Ln(2);
    }
    $pdf->Ln(3);
}

// Footer note
$pdf->SetY(-20);
$pdf->SetFont('Arial','I',10);
$pdf->Cell(0,10,"Generated by TasteIt Meal Planner",0,0,'C');

// Output PDF for download
$pdf->Output('D','TasteIt_Weekly_Grocery_List.pdf');
?>
